In [10]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np

In [11]:
vect = CountVectorizer(binary = True)
corpus= ["CNN is good optical character recognition","optical character recognition is significant"]
vect.fit(corpus)
print(vect.transform(corpus).toarray())

[[1 1 1 1 1 1 0]
 [1 0 0 1 1 1 1]]


In [12]:
vect = TfidfVectorizer()
corpus= ["CNN is good optical character recognition","optical character recognition is significant"]
vect.fit(corpus)
print(vect.transform(corpus).toarray())

[[0.35464863 0.49844628 0.49844628 0.35464863 0.35464863 0.35464863
  0.        ]
 [0.4090901  0.         0.         0.4090901  0.4090901  0.4090901
  0.57496187]]


In [13]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vect.transform(["Tessaeract is an optical character recognition system","optical character recognition system is significant"]))
print(similarity)

[[1.         0.81818021]
 [0.81818021 1.        ]]


In [14]:
vect = CountVectorizer(binary = True)
corpus= ["in February, the month of love as endowed by our great gifting industrial complex. we are wrestling with what 'love for travel' means in tangible, life affecting terms. The early throes of discovering travel might not be too dissimilar to the beginnings of a feverish affair A fleeting scene. sound or feeling that at first arouses, then enchants and eventually. lures us into a hypnotic state. evoking woolly-eyed reveries about what could be. This world. however. is not the most conducive for long-term passion, the kind that demands unflinching sustenance in the midst of distractions from a thousand notifications, Passion has many rivals to contend with. And in flippantly announcing travel as our first love, we are not fully considering the influence our other paramours (work, relationships or money) exert on us, Travellers for life are compulsive.","rekindles his passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland it's a near-precise rendering of the lrmeicgue as a self-help book A young Kaag was an avowed Nietzsche acolyte but given the ravages of responsibilities and adulthood the witer put his affinity to test by undertaking physically enduring hikesthrough the alps, revisiting haunts that the philosopher escaped to in search of solitude and salve The journey's demands. Coupled with his own inner turmoil, are catnip for anybody feeling at cross purposes with their own life"]
corp=vect.fit(corpus)
print(vect.transform(corpus).toarray())

[[1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1
  1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 1 0 0
  0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 1
  0 0 1 0 1 0 1 0 0 0 1 1 1 0 1 1 1 0 1 1 0 1 0 1 1 1 1 1 0 0 1 1 0 0 1 1
  0 1 1 0 0 1 1 1 1 1 0]
 [0 1 1 0 0 1 1 1 1 0 1 1 0 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0
  0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1
  1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0
  1 1 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0
  1 0 0 1 1 1 0 0 0 0 1]]


In [15]:
vect1 = TfidfVectorizer()
corpus= ["in February, the month of love as endowed by our great gifting industrial complex. we are wrestling with what 'love for travel' means in tangible, life affecting terms. The early throes of discovering travel might not be too dissimilar to the beginnings of a feverish affair A fleeting scene. sound or feeling that at first arouses, then enchants and eventually. lures us into a hypnotic state. evoking woolly-eyed reveries about what could be. This world. however. is not the most conducive for long-term passion, the kind that demands unflinching sustenance in the midst of distractions from a thousand notifications, Passion has many rivals to contend with. And in flippantly announcing travel as our first love, we are not fully considering the influence our other paramours (work, relationships or money) exert on us, Travellers for life are compulsive.","rekindles his passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland it's a near-precise rendering of the lrmeicgue as a self-help book A young Kaag was an avowed Nietzsche acolyte but given the ravages of responsibilities and adulthood the witer put his affinity to test by undertaking physically enduring hikesthrough the alps, revisiting haunts that the philosopher escaped to in search of solitude and salve The journey's demands. Coupled with his own inner turmoil, are catnip for anybody feeling at cross purposes with their own life"]
vect1.fit(corpus)
print(vect1.transform(corpus).toarray())

[[0.07100991 0.         0.         0.07100991 0.07100991 0.
  0.         0.         0.10104827 0.07100991 0.         0.15157241
  0.07100991 0.10104827 0.05052414 0.         0.14201982 0.07100991
  0.         0.         0.05052414 0.         0.07100991 0.07100991
  0.07100991 0.07100991 0.07100991 0.07100991 0.         0.
  0.05052414 0.07100991 0.07100991 0.07100991 0.07100991 0.07100991
  0.07100991 0.         0.         0.07100991 0.07100991 0.07100991
  0.07100991 0.07100991 0.05052414 0.07100991 0.14201982 0.07100991
  0.07100991 0.15157241 0.07100991 0.07100991 0.         0.07100991
  0.         0.07100991 0.07100991 0.         0.         0.
  0.         0.         0.07100991 0.07100991 0.20209655 0.07100991
  0.07100991 0.         0.07100991 0.07100991 0.         0.
  0.         0.07100991 0.10104827 0.07100991 0.21302974 0.
  0.07100991 0.07100991 0.07100991 0.07100991 0.07100991 0.07100991
  0.07100991 0.07100991 0.         0.         0.         0.21302974
  0.07100991 0.20209

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vect.transform(corpus))
print(similarity)

[[1.         0.18916706]
 [0.18916706 1.        ]]


In [17]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vect1.transform(corpus))
print(abs(similarity))

[[1.         0.36600426]
 [0.36600426 1.        ]]
